#!/bin/sh
 
#SBATCH --job-name=test_2_overfit_Obelleiro
#SBATCH --output=test_2_overfit_Obelleiro-%A.out  # Standard output of the script (Can be absolute or relative path). %A adds the job id to the file name so you can launch the same script multiple times and get different logging files
#SBATCH --error=test_2_overfit_Obelleiro-%A.err  # Standard error of the script
#SBATCH --time=0-0:30:00  # Limit on the total run time (format: days-hours:minutes:seconds)
#SBATCH --gres=gpu:1  # Number of GPUs if needed
#SBATCH --cpus-per-task=1  # Number of CPUs (Don't use more than 12/6 per GPU)
#SBATCH --mem=24G  # Memory in GB (Don't use more than 48/24 per GPU unless you absolutely need it and know what you are doing)
 
# run the program
ml cuda  # load default CUDA module

python image_train.py --data_dir ./data/asoca_dataset/assoca_sample --dataset_mode assoca --lr 1e-4 --batch_size 1 --attention_resolutions 32,16,8 --diffusion_steps 1000 --image_size 16 --learn_sigma True --noise_schedule linear --num_channels 128 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 False --use_scale_shift_norm True --use_checkpoint True --num_classes 1 --class_cond True --no_instance True --lr_anneal_steps 100

ml -cuda  # unload all modules